# Generated by Django 4.0.3 on 2022-04-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname',
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_time',
            field=models.IntegerField(default=0, verbose_name='Wymiar etatu'),
        ),
    ]
