# Generated by Django 4.0.3 on 2022-04-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0002_alter_organization_name'),
        ('accounts', '0002_remove_employee_name_remove_employee_surname_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user_unit',
            field=models.ManyToManyField(to='organizations.unit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_workplace',
            field=models.ManyToManyField(to='organizations.workplace'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa użytkownika'),
        ),
    ]
