# Generated by Django 4.0.3 on 2022-11-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_name'),
        ('accounts', '0003_alter_employee_managers_employee_user_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Czy jest kierownikiem?'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organizacja użytkownika'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_unit',
            field=models.ManyToManyField(to='organizations.unit', verbose_name='Jednostki użytkownika'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_workplace',
            field=models.ManyToManyField(to='organizations.workplace', verbose_name='Działy użytkownika'),
        ),
    ]
