# Generated by Django 4.0.3 on 2022-11-28 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_alter_employee_job_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['username'], 'verbose_name': 'Pracownik'},
        ),
    ]
