# Generated by Django 4.0.3 on 2022-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['order_number'], 'verbose_name': 'Pracownik'},
        ),
        migrations.AddField(
            model_name='employee',
            name='order_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Liczba porządkowa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_time',
            field=models.CharField(choices=[('1', '1'), ('3/4', '3/4'), ('1/2', '1/2'), ('1/4', '1/4')], default='1',
                                   max_length=3, verbose_name='Wymiar etatu'),
        ),
    ]
