# Generated by Django 4.0.3 on 2022-11-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_time',
            field=models.CharField(choices=[('1', '1'), ('3/4', '3/4'), ('1/2', '1/2'), ('1/4', '1/4')], default='1', max_length=3, verbose_name='Wymiar etatu'),
        ),
    ]
