# Generated by Django 4.0.3 on 2022-12-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_employee_job_time'),
        ('accounts', '0007_alter_employee_options_employee_order_number_and_more'),
    ]

    operations = [
    ]
