# Generated by Django 4.0.3 on 2022-12-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_name_alter_unit_name_and_more'),
        ('accounts', '0008_merge_20221203_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_unit',
            field=models.ManyToManyField(blank=True, to='organizations.unit', verbose_name='Jednostki użytkownika'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_workplace',
            field=models.ManyToManyField(blank=True, to='organizations.workplace', verbose_name='Działy użytkownika'),
        ),
    ]
