# Generated by Django 4.0.3 on 2023-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_alter_employee_user_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adres email'),
        ),
    ]
