FROM python:3.10.2

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY . .

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN groupadd -r app && useradd --no-log-init -r -g app app
RUN chown -R app:app .

RUN mkdir staticfiles
RUN chmod -R 600 staticfiles

USER app