# Generated by Django 4.0.3 on 2022-05-16 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Data rozpoczęcia')),
                ('date_end', models.DateField(verbose_name='Data zakończenia')),
                ('id_workplace',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workplace',
                                   verbose_name='Dział')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.TimeField(verbose_name='Czas rozpoczęcia zmiany')),
                ('hour_end', models.TimeField(verbose_name='Czas zakończenia zmiany')),
                ('name', models.CharField(max_length=512, verbose_name='Etykieta zmiany')),
                ('active_days', models.BinaryField(verbose_name='Aktywne dni')),
                ('is_algorithm', models.BooleanField(default=False)),
                ('is_archive', models.BooleanField(default=False)),
                ('id_workplace',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workplace',
                                   verbose_name='Dział')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data zmiany')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                               verbose_name='Pracownik')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule',
                                               verbose_name='Grafik')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shifttype',
                                                 verbose_name='Typ zmiany')),
            ],
        ),
    ]
