# Generated by Django 4.0.3 on 2022-05-16 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0002_alter_shifttype_active_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='id_workplace',
            new_name='workplace',
        ),
        migrations.RenameField(
            model_name='shifttype',
            old_name='id_workplace',
            new_name='workplace',
        ),
    ]
