# Generated by Django 4.0.3 on 2022-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0004_rename_is_algorithm_shifttype_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(default=5, verbose_name='Dzień'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2022, verbose_name='Rok'),
            preserve_default=False,
        ),
    ]
