# Generated by Django 4.0.3 on 2022-10-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0005_remove_schedule_date_end_remove_schedule_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(verbose_name='Miesiąc'),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_days', models.TextField(verbose_name='Aktywne dni')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                               verbose_name='Pracownik')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shifttype',
                                                 verbose_name='Typ zmiany')),
            ],
        ),
    ]
