# Generated by Django 4.0.3 on 2022-10-16 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0006_alter_schedule_month_preferences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Preference',
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Początek nieobecności')),
                ('end', models.DateField(verbose_name='Koniec nieobecności')),
                ('type', models.CharField(choices=[('SICK', 'Zwolnienie L4'), ('VAC', 'Vacation')], max_length=256,
                                          verbose_name='Typ nieobecności')),
                ('hours_number', models.IntegerField(verbose_name='Liczba godzin nieobecności')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                               verbose_name='Pracownik')),
            ],
        ),
    ]
