# Generated by Django 4.0.3 on 2022-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0007_rename_preferences_preference_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='employee_needed',
            field=models.IntegerField(default=1, verbose_name='Liczba pracowników'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type',
            field=models.CharField(choices=[('SICK', 'Zwolnienie L4'), ('VAC', 'Urlop wypoczynkowy')], max_length=256,
                                   verbose_name='Typ nieobecności'),
        ),
    ]
