# Generated by Django 4.0.3 on 2022-10-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0008_shifttype_employee_needed_alter_absence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='color',
            field=models.CharField(default='#BEDAFF', max_length=7, verbose_name='Kolor zmiany'),
        ),
    ]
