# Generated by Django 4.0.3 on 2022-10-22 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0009_shifttype_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifttype',
            old_name='employee_needed',
            new_name='demand',
        ),
    ]
