# Generated by Django 4.0.3 on 2022-11-24 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0011_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Rok')),
                ('january', models.IntegerField(verbose_name='Styczeń')),
                ('february', models.IntegerField(verbose_name='Luty')),
                ('march', models.IntegerField(verbose_name='Marzec')),
                ('april', models.IntegerField(verbose_name='Kwiecień')),
                ('may', models.IntegerField(verbose_name='Maj')),
                ('june', models.IntegerField(verbose_name='Czerwiec')),
                ('july', models.IntegerField(verbose_name='Lipiec')),
                ('august', models.IntegerField(verbose_name='Sierpień')),
                ('september', models.IntegerField(verbose_name='Wrzesień')),
                ('october', models.IntegerField(verbose_name='Październik')),
                ('november', models.IntegerField(verbose_name='Listopad')),
                ('december', models.IntegerField(verbose_name='Grudzień')),
            ],
        ),
        migrations.AlterField(
            model_name='absence',
            name='type',
            field=models.CharField(
                choices=[('SICK', 'Zwolnienie L4'), ('VAC', 'Urlop wypoczynkowy'), ('OTHER', 'Inne')], max_length=256,
                verbose_name='Typ nieobecności'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('shift_type', 'employee', 'start', 'end', 'negative_flag')},
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('shift_type', 'employee', 'active_days')},
        ),
    ]
