# Generated by Django 4.0.3 on 2022-11-28 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0012_jobtime_alter_absence_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('employee', 'start', 'end')},
        ),
    ]
