# Generated by Django 4.0.3 on 2022-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_freeday'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeday',
            name='name',
            field=models.CharField(default='a', max_length=256, verbose_name='Nazwa wolnego'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freeday',
            name='day',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
    ]
