# Generated by Django 4.0.3 on 2022-12-09 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0006_alter_organization_options_alter_unit_options_and_more'),
        ('schedules', '0015_freeday_name_alter_freeday_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='freeday',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['month']},
        ),
        migrations.AlterModelOptions(
            name='shifttype',
            options={'ordering': ['hour_start']},
        ),
        migrations.CreateModel(
            name='AlgorithmTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField()),
                ('process_pid', models.IntegerField()),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
    ]
