# Generated by Django 4.0.3 on 2022-12-09 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0016_alter_absence_options_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmtask',
            name='is_running',
        ),
    ]
