# Generated by Django 4.0.3 on 2022-12-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0017_remove_algorithmtask_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmtask',
            name='process_pid',
            field=models.CharField(max_length=2048),
        ),
    ]
