# Generated by Django 4.0.3 on 2022-12-12 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0006_alter_organization_options_alter_unit_options_and_more'),
        ('schedules', '0018_alter_algorithmtask_process_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeday',
            options={},
        ),
        migrations.AddField(
            model_name='freeday',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='organizations.organization', verbose_name='Organizacja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobtime',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='organizations.organization', verbose_name='Organizacja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freeday',
            name='day',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='jobtime',
            name='year',
            field=models.IntegerField(verbose_name='Rok'),
        ),
        migrations.AlterUniqueTogether(
            name='freeday',
            unique_together={('organization', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtime',
            unique_together={('organization', 'year')},
        ),
    ]
