# Generated by Django 4.0.3 on 2022-12-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0019_alter_freeday_options_freeday_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='shift_code',
            field=models.CharField(default='AAA', max_length=3, verbose_name='Krótka nazwa zmiany'),
            preserve_default=False,
        ),
    ]
