# Generated by Django 4.0.3 on 2023-01-11 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0021_schedule_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='message',
        ),
    ]
