# Generated by Django 4.0.3 on 2023-01-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0022_remove_schedule_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttype',
            name='color',
            field=models.CharField(blank=True, default='#BEDAFF', max_length=7, null=True, verbose_name='Kolor zmiany'),
        ),
    ]
