# Generated by Django 4.0.3 on 2022-11-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Początek zamknięcia')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Koniec zamknięcia')),
                ('workplace',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workplace',
                                   verbose_name='Dział')),
            ],
        ),
    ]
