# Generated by Django 4.0.3 on 2022-11-28 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0003_workplaceclosing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='allow_preferences',
        ),
    ]
