# Generated by Django 4.0.3 on 2022-11-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0004_remove_unit_allow_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Nazwa organizacji'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Nazwa jednostki'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Nazwa działu'),
        ),
    ]
