# Generated by Django 4.0.3 on 2022-12-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0005_alter_organization_name_alter_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workplaceclosing',
            options={'ordering': ['start']},
        ),
        migrations.AlterField(
            model_name='workplaceclosing',
            name='end',
            field=models.DateField(verbose_name='Koniec zamknięcia'),
        ),
        migrations.AlterField(
            model_name='workplaceclosing',
            name='start',
            field=models.DateField(verbose_name='Początek zamknięcia'),
        ),
    ]
