# Generated by Django 4.0.3 on 2023-01-10 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0006_alter_organization_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workplaceclosing',
            unique_together={('workplace', 'start', 'end')},
        ),
    ]
